services:

  mongo:
    container_name: ${MONGO_DATABASE}
    image: mongo:8.0.3-noble
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
      - ./core/database/tnlcm-structure.js:/docker-entrypoint-initdb.d/tnlcm-structure.js
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - path: .env
        required: true

  mongo-express:
    container_name: ${MONGO_DATABASE}-frontend
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - mongo
    env_file:
      - path: .env
        required: true

  tnlcm:
    container_name: tnlcm
    image: tnlcm:0.4.2
    ports:
      - ${TNLCM_PORT}:${TNLCM_PORT}
    build: 
      context: .
      dockerfile: docker/flask/Dockerfile
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - mongo-express
    env_file:
      - path: .env
        required: true

volumes:
  mongo-data:
  mongo-config: