services:

  mongo:
    container_name: ${MONGO_DATABASE}
    image: mongo:7.0.11-jammy
    ports:
      - 27017:27017
    volumes:
      - data:/var/lib/mongodb_data
      - ./core/database/tnlcm-structure.js:/docker-entrypoint-initdb.d/tnlcm-structure.js
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}

  mongo-express:
    container_name: ${MONGO_DATABASE}-frontend
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}

volumes:
  data: