from core.logs.log_handler import console_logger
from core.utils.os import get_dotenv_var


class MongoDBSettings:
    """
    MongoDB Settings
    """

    MONGO_DATABASE = get_dotenv_var(key="MONGO_DATABASE")
    MONGO_HOST = get_dotenv_var(key="MONGO_HOST")
    MONGO_PORT = get_dotenv_var(key="MONGO_PORT")
    ME_CONFIG_BASICAUTH = get_dotenv_var(key="ME_CONFIG_BASICAUTH")
    ME_CONFIG_BASICAUTH_PASSWORD = get_dotenv_var(key="ME_CONFIG_BASICAUTH_PASSWORD")
    ME_CONFIG_BASICAUTH_USERNAME = get_dotenv_var(key="ME_CONFIG_BASICAUTH_USERNAME")
    ME_CONFIG_MONGODB_ADMINUSERNAME = get_dotenv_var(
        key="ME_CONFIG_MONGODB_ADMINUSERNAME"
    )
    ME_CONFIG_MONGODB_ADMINPASSWORD = get_dotenv_var(
        key="ME_CONFIG_MONGODB_ADMINPASSWORD"
    )
    ME_CONFIG_MONGODB_ENABLE_ADMIN = get_dotenv_var(
        key="ME_CONFIG_MONGODB_ENABLE_ADMIN"
    )
    ME_CONFIG_MONGODB_URL = get_dotenv_var(key="ME_CONFIG_MONGODB_URL")
    ME_CONFIG_SITE_SESSIONSECRET = get_dotenv_var(key="ME_CONFIG_SITE_SESSIONSECRET")
    VCAP_APP_HOST = get_dotenv_var(key="VCAP_APP_HOST")

    config_dict = {
        "MONGO_DATABASE": MONGO_DATABASE,
        "MONGO_HOST": MONGO_HOST,
        "MONGO_PORT": MONGO_PORT,
        "ME_CONFIG_BASICAUTH": ME_CONFIG_BASICAUTH,
        "ME_CONFIG_BASICAUTH_PASSWORD": ME_CONFIG_BASICAUTH_PASSWORD,
        "ME_CONFIG_BASICAUTH_USERNAME": ME_CONFIG_BASICAUTH_USERNAME,
        "ME_CONFIG_MONGODB_ADMINUSERNAME": ME_CONFIG_MONGODB_ADMINUSERNAME,
        "ME_CONFIG_MONGODB_ADMINPASSWORD": ME_CONFIG_MONGODB_ADMINPASSWORD,
        "ME_CONFIG_MONGODB_ENABLE_ADMIN": ME_CONFIG_MONGODB_ENABLE_ADMIN,
        "ME_CONFIG_MONGODB_URL": ME_CONFIG_MONGODB_URL,
        "ME_CONFIG_SITE_SESSIONSECRET": ME_CONFIG_SITE_SESSIONSECRET,
        "VCAP_APP_HOST": VCAP_APP_HOST,
    }

    console_logger.info(f"Load MongoDB configuration: {config_dict}")
