import os
import threading

from flask_restx import Namespace, Resource, reqparse, abort
from flask_jwt_extended import jwt_required, get_jwt_identity
from werkzeug.datastructures import FileStorage
from mongoengine.errors import ValidationError, MongoEngineException
from jenkins import JenkinsException

from core.logs.log_handler import log_handler
from core.auth.auth import get_current_user_from_jwt
from conf import TnlcmSettings
from core.callback.callback_handler import CallbackHandler
from core.jenkins.jenkins_handler import JenkinsHandler
from core.models import TrialNetworkModel, ResourceManagerModel
from core.sixg_library.sixg_library_handler import SixGLibraryHandler
from core.sixg_sandbox_sites.sixg_sandbox_sites_handler import SixGSandboxSitesHandler

from core.exceptions.exceptions_handler import CustomException

trial_network_namespace = Namespace(
    name="trial-network",
    description="Namespace for trial network status and management",
    authorizations={
        "Bearer Auth": {
            "type": "apiKey",
            "in": "header",
            "name": "Authorization"
        }
    }
)

##########################################
############ Mutual exclusion ############
##########################################
tn_id_lock = threading.Lock()
tn_resource_manager_lock = threading.Lock()

#################################
######### Trial Network #########
#################################
@trial_network_namespace.route("")
class CreateTrialNetwork(Resource):

    parser_post = reqparse.RequestParser()
    parser_post.add_argument("tn_id", type=str, required=False)
    parser_post.add_argument("descriptor", location="files", type=FileStorage, required=True)
    parser_post.add_argument("deployment_site", type=str, required=True)
    parser_post.add_argument("github_6g_library_reference_type", type=str, required=True, choices=("branch", "commit", "tag"))
    parser_post.add_argument("github_6g_library_reference_value", type=str, required=True)
    parser_post.add_argument("github_6g_sandbox_sites_reference_type", type=str, required=True, choices=("branch", "commit", "tag"))
    parser_post.add_argument("github_6g_sandbox_sites_reference_value", type=str, required=True)

    @trial_network_namespace.doc(security="Bearer Auth")
    @jwt_required()
    @trial_network_namespace.expect(parser_post)
    def post(self) -> tuple[dict, int]:
        """
        Create and validate trial network
        Can specify a branch, commit or tag of the 6G-Library.
        Can specify a branch, commit or tag of the 6G-Sandbox-Sites.
        The tn_id can be specified if desired. **If the value is specified, it should begin with character. If nothing is specified, it will return a random tn_id.**
        """
        try:
            tn_id = self.parser_post.parse_args()["tn_id"]
            tn_descriptor_file = self.parser_post.parse_args()["descriptor"]
            deployment_site = self.parser_post.parse_args()["deployment_site"]
            github_6g_library_reference_type = self.parser_post.parse_args()["github_6g_library_reference_type"]
            github_6g_library_reference_value = self.parser_post.parse_args()["github_6g_library_reference_value"]
            github_6g_sandbox_sites_reference_type = self.parser_post.parse_args()["github_6g_sandbox_sites_reference_type"]
            github_6g_sandbox_sites_reference_value = self.parser_post.parse_args()["github_6g_sandbox_sites_reference_value"]

            current_user = get_current_user_from_jwt(get_jwt_identity())
            trial_network = TrialNetworkModel(user_created=current_user.username)
            with tn_id_lock:
                trial_network.set_tn_id(size=3, tn_id=tn_id)
                log_handler.info(f"Trial network created with identifier '{trial_network.tn_id}'")
            tn_folder = os.path.join(TnlcmSettings.TRIAL_NETWORKS_DIRECTORY, f"{trial_network.tn_id}")
            trial_network.set_tn_folder(tn_folder)
            log_handler.info(f"[{trial_network.tn_id}] - Create the folder '{trial_network.tn_id}' in the path '{trial_network.tn_folder}' to store the directories and files generated by the trial network")
            trial_network.set_tn_raw_descriptor(tn_descriptor_file)
            log_handler.info(f"[{trial_network.tn_id}] - Trial network descriptor raw saved")
            log_handler.info(f"[{trial_network.tn_id}] - Apply the sorting algorithm according to the dependencies of the components specified in the trial network descriptor")
            trial_network.set_tn_sorted_descriptor()
            log_handler.info(f"[{trial_network.tn_id}] - Trial network descriptor sorted")
            sixg_sandbox_sites_handler = SixGSandboxSitesHandler(reference_type=github_6g_sandbox_sites_reference_type, reference_value=github_6g_sandbox_sites_reference_value, tn_folder=tn_folder)
            sixg_sandbox_sites_handler.git_clone()
            log_handler.info(f"[{trial_network.tn_id}] - Git clone '{sixg_sandbox_sites_handler.github_6g_sandbox_sites_repository_name}' repository into '{trial_network.tn_folder}'")
            sixg_sandbox_sites_handler.git_checkout()
            log_handler.info(f"[{trial_network.tn_id}] - Git status '{sixg_sandbox_sites_handler.github_6g_sandbox_sites_repository_name}' repository into '{trial_network.tn_folder}' with HEAD pointing to commit '{sixg_sandbox_sites_handler.github_6g_sandbox_sites_commit_id}'")
            log_handler.info(f"[{trial_network.tn_id}] - Validate deployment site '{deployment_site}'")
            sixg_sandbox_sites_handler.validate_site(deployment_site)
            trial_network.set_deployment_site(deployment_site)
            log_handler.info(f"[{trial_network.tn_id}] - Deployment site '{trial_network.deployment_site}' is valid")
            tn_components_types = trial_network.get_tn_components_types()
            log_handler.info(f"[{trial_network.tn_id}] - Validate if the components that make up the descriptor are available on the deployment site '{trial_network.deployment_site}'")
            sixg_sandbox_sites_handler.validate_components_site(tn_id=trial_network.tn_id, deployment_site=trial_network.deployment_site, tn_components_types=tn_components_types)
            log_handler.info(f"[{trial_network.tn_id}] - Descriptor components are available on the deployment site '{trial_network.deployment_site}'")
            sixg_library_handler = SixGLibraryHandler(reference_type=github_6g_library_reference_type, reference_value=github_6g_library_reference_value, tn_folder=tn_folder)
            sixg_library_handler.git_clone()
            log_handler.info(f"[{trial_network.tn_id}] - Git clone '{sixg_library_handler.github_6g_library_repository_name}' repository into '{trial_network.tn_folder}'")
            sixg_library_handler.git_checkout()
            log_handler.info(f"[{trial_network.tn_id}] - Git status '{sixg_library_handler.github_6g_library_repository_name}' repository into '{trial_network.tn_folder}' with HEAD pointing to commit '{sixg_library_handler.github_6g_library_commit_id}'")
            tn_component_inputs = sixg_library_handler.get_tn_components_parts(deployment_site=deployment_site, parts=["input"], tn_components_types=tn_components_types)["input"]
            log_handler.info(f"[{trial_network.tn_id}] - Validate trial network descriptor")
            trial_network.validate_tn_descriptor(tn_components_types, tn_component_inputs)
            log_handler.info(f"[{trial_network.tn_id}] - Trial network descriptor valid")
            trial_network.set_github_6g_library_commit_id(sixg_library_handler.github_6g_library_commit_id)
            trial_network.set_github_6g_sandbox_sites_commit_id(sixg_sandbox_sites_handler.github_6g_sandbox_sites_commit_id)
            trial_network.set_tn_state("validated")
            trial_network.save()
            log_handler.info(f"[{trial_network.tn_id}] - Trial network update to status '{trial_network.tn_state}'")
            return trial_network.to_dict(), 201
        except ValidationError as e:
            return abort(401, e.message)
        except MongoEngineException as e:
            return abort(401, str(e))
        except CustomException as e:
            return abort(e.error_code, str(e))

@trial_network_namespace.route("/<string:tn_id>")
class TrialNetwork(Resource):

    @trial_network_namespace.doc(security="Bearer Auth")
    @jwt_required()
    def get(self, tn_id: str) -> tuple[dict, int]:
        """
        Return trial network
        """
        try:
            current_user = get_current_user_from_jwt(get_jwt_identity())
            if current_user.role == "admin":
                trial_network = TrialNetworkModel.objects(tn_id=tn_id).first()
            else:
                trial_network = TrialNetworkModel.objects(user_created=current_user.username, tn_id=tn_id).first()
            if not trial_network:
                return abort(404, f"No trial network with the name '{tn_id}' created by the user '{current_user.username}'")
            return trial_network.to_dict_full(), 200
        except CustomException as e:
            return abort(e.error_code, str(e))
    
    parser_put = reqparse.RequestParser()
    parser_put.add_argument("jenkins_deploy_pipeline", type=str, required=False)

    @trial_network_namespace.doc(security="Bearer Auth")
    @jwt_required()
    @trial_network_namespace.expect(parser_put)
    def put(self, tn_id: str) -> tuple[dict, int]:
        """
        STATE MACHINE: play or suspend trial network
        If nothing is specified in jenkins_deploy_pipeline, a pipeline will be created inside TNLCM folder in Jenkins with the name **TN_DEPLOY_<tn_id>**
        If a deployment pipeline is specified, it will be checked that it exists in Jenkins and that it has nothing queued to execute
        """
        try:
            jenkins_deploy_pipeline = self.parser_put.parse_args()["jenkins_deploy_pipeline"]

            current_user = get_current_user_from_jwt(get_jwt_identity())
            if current_user.role == "admin":
                trial_network = TrialNetworkModel.objects(tn_id=tn_id).first()
            else:
                trial_network = TrialNetworkModel.objects(user_created=current_user.username, tn_id=tn_id).first()
            if not trial_network:
                return abort(404, f"No trial network with the name '{tn_id}' created by the user '{current_user}'")
            
            tn_state = trial_network.tn_state
            if tn_state == "validated":
                callback_handler = CallbackHandler(trial_network=trial_network)
                jenkins_handler = JenkinsHandler(trial_network=trial_network, callback_handler=callback_handler)
                jenkins_deploy_pipeline = jenkins_handler.generate_jenkins_deploy_pipeline(jenkins_deploy_pipeline)
                trial_network.set_jenkins_deploy_pipeline(jenkins_deploy_pipeline)
                trial_network.save()
                log_handler.info(f"[{trial_network.tn_id}] - Created '{trial_network.jenkins_deploy_pipeline}' pipeline in Jenkins to deploy the trial network")
                sixg_sandbox_sites_handler = SixGSandboxSitesHandler(reference_type="commit", reference_value=trial_network.github_6g_sandbox_sites_commit_id, tn_folder=trial_network.tn_folder)
                site_available_components = sixg_sandbox_sites_handler.get_site_available_components(deployment_site=trial_network.deployment_site)
                log_handler.info(f"[{trial_network.tn_id}] - Apply resource manager")
                resource_manager = ResourceManagerModel()
                with tn_resource_manager_lock:
                    resource_manager.apply_resource_manager(trial_network, site_available_components)
                    log_handler.info(f"[{trial_network.tn_id}] - Resource manager is applied")
                log_handler.info(f"[{trial_network.tn_id}] - Start deployment of the trial network using Jenkins")
                jenkins_handler.trial_network_deployment()
                log_handler.info(f"[{trial_network.tn_id}] - End deployment of the trial network using Jenkins")
                trial_network.set_tn_report(callback_handler.get_path_tn_report_markdown())
                trial_network.set_tn_state("activated")
                trial_network.save()
                log_handler.info(f"[{trial_network.tn_id}] - Trial network update to status '{trial_network.tn_state}'")
                return {"message": f"Trial network activated. Report of the trial network can be found in the directory '{trial_network.tn_folder}/{trial_network.tn_id}'.md"}, 200
            elif tn_state == "failed":
                callback_handler = CallbackHandler(trial_network=trial_network)
                jenkins_handler = JenkinsHandler(trial_network=trial_network, callback_handler=callback_handler)
                first_key = next(iter(trial_network.json_to_descriptor(trial_network.tn_deployed_descriptor)["trial_network"]))
                log_handler.info(f"[{trial_network.tn_id}] - Deployment of the trial network continues in the entity_name '{first_key}'")
                jenkins_handler.trial_network_deployment()
                log_handler.info(f"[{trial_network.tn_id}] - End deployment of the trial network using Jenkins")
                trial_network.set_tn_report(callback_handler.get_path_tn_report_markdown())
                trial_network.set_tn_state("activated")
                trial_network.save()
                log_handler.info(f"[{trial_network.tn_id}] - Trial network update to status '{trial_network.tn_state}'")
                return {"message": f"Trial network activated. Report of the trial network can be found in the directory '{trial_network.tn_folder}/{trial_network.tn_id}'.md"}, 200
            elif tn_state == "destroyed":
                callback_handler = CallbackHandler(trial_network=trial_network)
                jenkins_handler = JenkinsHandler(trial_network=trial_network, callback_handler=callback_handler)
                sixg_sandbox_sites_handler = SixGSandboxSitesHandler(reference_type="commit", reference_value=trial_network.github_6g_sandbox_sites_commit_id, tn_folder=trial_network.tn_folder)
                site_available_components = sixg_sandbox_sites_handler.get_site_available_components(deployment_site=trial_network.deployment_site)
                log_handler.info(f"[{trial_network.tn_id}] - Apply resource manager")
                resource_manager = ResourceManagerModel()
                with tn_resource_manager_lock:
                    resource_manager.apply_resource_manager(trial_network, site_available_components)
                    log_handler.info(f"[{trial_network.tn_id}] - Resource manager is applied")
                log_handler.info(f"[{trial_network.tn_id}] - Start again deployment of the trial network using Jenkins")
                jenkins_handler.trial_network_deployment(trial_network.jenkins_deploy_pipeline)
                log_handler.info(f"[{trial_network.tn_id}] - End deployment of the trial network using Jenkins")
                trial_network.set_tn_report(callback_handler.get_path_tn_report_markdown())
                trial_network.set_tn_state("activated")
                trial_network.save()
                log_handler.info(f"[{trial_network.tn_id}] - Trial network update to status '{trial_network.tn_state}'")
                return {"message": f"Trial network activated. Report of the trial network can be found in the directory '{trial_network.tn_folder}/{trial_network.tn_id}'.md"}, 200
            elif tn_state == "activated":
                # TODO: see what to do with trial network resources
                return {"message": "TODO: suspend trial network"}, 400
            else: # tn_state == "suspended"
                # TODO:
                return {"message": "TODO: restart trial network suspended"}, 400
        except ValidationError as e:
            return abort(401, e.message)
        except MongoEngineException as e:
            return abort(401, str(e))
        except JenkinsException as e:
            return abort(401, str(e))
        except CustomException as e:
            return abort(e.error_code, str(e))

    parser_delete = reqparse.RequestParser()
    parser_delete.add_argument("jenkins_destroy_pipeline", type=str, required=False)

    @trial_network_namespace.doc(security="Bearer Auth")
    @jwt_required()
    @trial_network_namespace.expect(parser_delete)
    def delete(self, tn_id: str) -> tuple[dict, int]:
        """
        Delete trial network
        If nothing is specified in jenkins_destroy_pipeline, a pipeline will be created inside TNLCM folder in Jenkins with the name **TN_DESTROY_<tn_id>**
        If a destroy pipeline is specified, it will be checked that it exists in Jenkins and that it has nothing queued to execute
        """
        try:
            jenkins_destroy_pipeline = self.parser_delete.parse_args()["jenkins_destroy_pipeline"]

            current_user = get_current_user_from_jwt(get_jwt_identity())
            if current_user.role == "admin":
                trial_network = TrialNetworkModel.objects(tn_id=tn_id).first()
            else:
                trial_network = TrialNetworkModel.objects(user_created=current_user.username, tn_id=tn_id).first()
            if not trial_network:
                return abort(404, f"No trial network with the name '{tn_id}' created by the user '{current_user}'")
            
            tn_state = trial_network.tn_state
            if tn_state != "activated":
                return abort(400, f"Trial network cannot be destroyed because the current status of Trial Network is different to ACTIVATED")
            callback_handler = CallbackHandler(trial_network=trial_network)
            sixg_library_handler = SixGLibraryHandler(reference_type="commit", reference_value=trial_network.github_6g_library_commit_id, tn_folder=trial_network.tn_folder)
            jenkins_handler = JenkinsHandler(trial_network=trial_network, callback_handler=callback_handler, sixg_library_handler=sixg_library_handler)
            log_handler.info(f"[{trial_network.tn_id}] - Validate pipeline use for destroy trial network '{jenkins_destroy_pipeline}'")
            jenkins_destroy_pipeline = jenkins_handler.generate_jenkins_destroy_pipeline(jenkins_destroy_pipeline=jenkins_destroy_pipeline)
            trial_network.set_jenkins_destroy_pipeline(jenkins_destroy_pipeline)
            trial_network.save()
            log_handler.info(f"[{trial_network.tn_id}] - Pipeline for destroy trial network '{trial_network.jenkins_destroy_pipeline}' is valid")
            log_handler.info(f"[{trial_network.tn_id}] - Start destroy of the trial network using Jenkins")
            jenkins_handler.trial_network_destroy(jenkins_destroy_pipeline=trial_network.jenkins_destroy_pipeline)
            log_handler.info(f"[{trial_network.tn_id}] - End destroy of the trial network using Jenkins")
            log_handler.info(f"[{trial_network.tn_id}] - Apply release resource manager")
            resource_manager = ResourceManagerModel()
            with tn_resource_manager_lock:
                resource_manager.release_resource_manager(trial_network)
                log_handler.info(f"[{trial_network.tn_id}] - Release resource manager is applied")
            trial_network.set_tn_deployed_descriptor()
            trial_network.set_tn_state("destroyed")
            trial_network.save()
            log_handler.info(f"[{trial_network.tn_id}] - Trial network update to status '{trial_network.tn_state}'")
            return {"message": f"The trial network with identifier '{tn_id}' has been destroyed"}, 200
        except ValidationError as e:
            return abort(401, e.message)
        except MongoEngineException as e:
            return abort(401, str(e))
        except JenkinsException as e:
            return abort(401, str(e))
        except CustomException as e:
            return abort(e.error_code, str(e))

@trial_network_namespace.route("/report/<string:tn_id>")
class TrialNetworkReport(Resource):

    @trial_network_namespace.doc(security="Bearer Auth")
    @jwt_required()
    def get(self, tn_id: str) -> tuple[dict, int]:
        """
        Return the report generated after the execution of the entities of a trial network
        """
        try:
            current_user = get_current_user_from_jwt(get_jwt_identity())
            if current_user.role == "admin":
                trial_network = TrialNetworkModel.objects(tn_id=tn_id).first()
            else:
                trial_network = TrialNetworkModel.objects(user_created=current_user.username, tn_id=tn_id).first()
            if not trial_network:
                return abort(404, f"No trial network with the name '{tn_id}' created by the user '{current_user}'")
            return {"tn_report": trial_network.tn_report}, 200
        except CustomException as e:
            return abort(e.error_code, str(e))

@trial_network_namespace.route("s/") 
class TrialNetworks(Resource):

    @trial_network_namespace.doc(security="Bearer Auth")
    @jwt_required()
    def get(self) -> tuple[dict, int]:
        """
        Return information of all trial networks stored in database created by user identified
        """
        try:
            current_user = get_current_user_from_jwt(get_jwt_identity())
            if current_user.role == "admin":
                trial_networks = TrialNetworkModel.objects()
            else:
                trial_networks = TrialNetworkModel.objects(user_created=current_user.username)
            return {'trial_networks': [tn.to_dict_full() for tn in trial_networks]}, 200
        except CustomException as e:
            return abort(e.error_code, str(e))