name: Python Project

env:
  FLASK_ENV: ${{ secrets.FLASK_ENV }}
  JENKINS_SERVER: ${{ secrets.JENKINS_SERVER }}
  JENKINS_USER: ${{ secrets.JENKINS_USER }}
  JENKINS_PASSWORD: ${{ secrets.JENKINS_PASSWORD }}
  JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
  JENKINS_TN_JOB_NAME: ${{ secrets.JENKINS_TN_JOB_NAME }}
  JENKINS_DEPLOYMENT_SITE: ${{ secrets.JENKINS_DEPLOYMENT_SITE }}
  CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
  MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
  MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
  MONGO_HOST: ${{ secrets.MONGO_HOST }}
  MONGO_PORT: ${{ secrets.MONGO_PORT }}
  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
  ME_CONFIG_MONGODB_ADMINUSERNAME: ${{ secrets.ME_CONFIG_MONGODB_ADMINUSERNAME }}
  ME_CONFIG_MONGODB_ADMINPASSWORD: ${{ secrets.ME_CONFIG_MONGODB_ADMINPASSWORD }}
  GIT_6GLIBRARY_HTTPS_URL: ${{ secrets.GIT_6GLIBRARY_HTTPS_URL }}
  GIT_6GLIBRARY_BRANCH: ${{ secrets.GIT_6GLIBRARY_BRANCH }}
  GIT_6GLIBRARY_REPOSITORY_NAME: ${{ secrets.GIT_6GLIBRARY_REPOSITORY_NAME }}
  MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
  MAIL_PORT: ${{ secrets.MAIL_PORT }}
  MAIL_USE_TLS: ${{ secrets.MAIL_USE_TLS }}
  MAIL_USE_SSL: ${{ secrets.MAIL_USE_SSL }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create .env file
        run: |
          echo "FLASK_ENV=${FLASK_ENV}" > .env
          echo "JENKINS_SERVER=${JENKINS_SERVER}" >> .env
          echo "JENKINS_USER=${JENKINS_USER}" >> .env
          echo "JENKINS_PASSWORD=${JENKINS_PASSWORD}" >> .env
          echo "JENKINS_TOKEN=${JENKINS_TOKEN}" >> .env
          echo "JENKINS_TN_JOB_NAME=${JENKINS_TN_JOB_NAME}" >> .env
          echo "JENKINS_DEPLOYMENT_SITE=${JENKINS_DEPLOYMENT_SITE}" >> .env
          echo "CALLBACK_URL=${CALLBACK_URL}" >> .env
          echo "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}" >> .env
          echo "MONGO_HOST=${MONGO_HOST}" >> .env
          echo "MONGO_PORT=${MONGO_PORT}" >> .env
          echo "MONGO_DATABASE=${MONGO_DATABASE}" >> .env
          echo "ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}" >> .env
          echo "ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}" >> .env
          echo "GIT_6GLIBRARY_HTTPS_URL=${GIT_6GLIBRARY_HTTPS_URL}" >> .env
          echo "GIT_6GLIBRARY_BRANCH=${GIT_6GLIBRARY_BRANCH}" >> .env
          echo "GIT_6GLIBRARY_REPOSITORY_NAME=${GIT_6GLIBRARY_REPOSITORY_NAME}" >> .env
          echo "MAIL_SERVER=${MAIL_SERVER}" >> .env
          echo "MAIL_PORT=${MAIL_PORT}" >> .env
          echo "MAIL_USE_TLS=${MAIL_USE_TLS}" >> .env
          echo "MAIL_USE_SSL=${MAIL_USE_SSL}" >> .env
          echo "MAIL_USERNAME=${MAIL_USERNAME}" >> .env
          echo "MAIL_PASSWORD=${MAIL_PASSWORD}" >> .env
      - name: Start server
        run: |
          source .env && python3 app.py
      - name: Run tests
        run: |
          pytest tests/