name: Lint code with ruff

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'
      - 'tn_template_lib/**'
      - 'README'
      - 'LICENSE'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'
      - 'tn_template_lib/**'
      - 'README'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Analysing the code with ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: "check"